[package]
name = "cw-multi-test"
version = "0.16.5"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2021"
description = "Test helpers for multi-contract interactions"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-multi-test"
homepage = "https://cosmwasm.com"

[features]
default = ["iterator", "staking", "cosmwasm_1_1"]
iterator = ["cosmwasm-std/iterator"]
stargate = ["cosmwasm-std/stargate"]
staking = ["cosmwasm-std/staking"]
backtrace = ["anyhow/backtrace"]
cosmwasm_1_1 = ["cosmwasm-std/cosmwasm_1_1"]
cosmwasm_1_2 = ["cosmwasm_1_1", "cosmwasm-std/cosmwasm_1_2"]
cosmwasm_1_3 = ["cosmwasm_1_2", "cosmwasm-std/cosmwasm_1_3"]

[dependencies]
cw-utils = "1.0"
cw-storage-plus = "1.1"
cosmwasm-std = { version = "1.3", features = ["staking", "stargate"] }
itertools = "0.11"
schemars = "0.8.1"
serde = { version = "1.0", default-features = false, features = ["derive"] }
prost = "0.11"
anyhow = "1.0"
thiserror = "1.0"
derivative = "2"

[dev-dependencies]
serde_json = "1.0.40"
