[package]

name = "abstract-cw-multi-test"
version = "0.17.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2021"
description = "Test helpers for multi-contract interactions with ibc capabilities"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-multi-test"
homepage = "https://cosmwasm.com"

[features]
default = ["iterator", "staking", "cosmwasm_1_2"]
iterator = ["cosmwasm-std/iterator"]
stargate = ["cosmwasm-std/stargate"]
staking = ["cosmwasm-std/staking"]
backtrace = ["anyhow/backtrace"]
cosmwasm_1_1 = ["cosmwasm-std/cosmwasm_1_1", "cosmwasm-std/ibc3"]
cosmwasm_1_2 = ["cosmwasm_1_1", "cosmwasm-std/cosmwasm_1_2"]
cosmwasm_1_3 = ["cosmwasm_1_2", "cosmwasm-std/cosmwasm_1_3"]
cosmwasm_1_4 = ["cosmwasm_1_3", "cosmwasm-std/cosmwasm_1_4"]

[dependencies]
anyhow = "1.0.75"
cosmwasm-std = { version = "1.5.0", features = ["staking", "stargate"] }
cw-storage-plus = "1.1.0"
cw-utils = "1.0.2"
derivative = "2.2.0"
itertools = "0.11.0"
prost = "0.12.1"
schemars = "0.8.15"
serde = { version = "1.0.188", default-features = false, features = ["derive"] }
sha2 = "0.10.8"
thiserror = "1.0.49"

cosmwasm-schema = "1.3.3"
log = "0.4.20"
cw20-ics20 = "1.1.0"
hex = "0.4.3"
serde_json = "1.0.40"

sha256 = "1.4.0"
bech32 = "0.9.1"

[dev-dependencies]
bech32 = "0.9.1"
once_cell = "1.18.0"

# We don't use these dependencies directly,
# we tighten versions that builds with `-Zminimal-versions` work.
ecdsa = "0.16.8"

env_logger = "0.10.0"
polytone-note = {version="1.0.0" }
polytone-voice = {version="1.0.0" }
polytone-proxy = {version="1.0.0" }
polytone = {version="1.0.0" }
