[package]
name = "cw-multi-test"
version = "0.18.1"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2021"
description = "Test helpers for multi-contract interactions"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-multi-test"
homepage = "https://cosmwasm.com"

[features]
default = ["iterator", "staking"]
iterator = ["cosmwasm-std/iterator"]
stargate = ["cosmwasm-std/stargate"]
staking = ["cosmwasm-std/staking"]
backtrace = ["anyhow/backtrace"]
cosmwasm_1_1 = ["cosmwasm-std/cosmwasm_1_1"]
cosmwasm_1_2 = ["cosmwasm_1_1", "cosmwasm-std/cosmwasm_1_2"]
cosmwasm_1_3 = ["cosmwasm_1_2", "cosmwasm-std/cosmwasm_1_3"]
cosmwasm_1_4 = ["cosmwasm_1_3", "cosmwasm-std/cosmwasm_1_4"]

[dependencies]
anyhow = "1.0.75"
cosmwasm-std = { version = "1.5.0", features = ["staking", "stargate"] }
cw-storage-plus = "1.2.0"
cw-utils = "1.0.2"
derivative = "2.2.0"
itertools = "0.12.0"
prost = "0.12.2"
schemars = "0.8.16"
serde = { version = "1.0.193", default-features = false, features = ["derive"] }
sha2 = "0.10.8"
thiserror = "1.0.50"

[dev-dependencies]
bech32 = "0.9.1"
once_cell = "1.18.0"
sha2 = "0.10.8"
