[package]
name = "abstract-cw-multi-test"
version = "2.0.0"
authors = [
    "Ethan Frey <ethanfrey@users.noreply.github.com>",
    "Dariusz Depta <DariuszDepta@users.noreply.github.com>",
]
description = "Testing tools for multi-contract interactions"
repository = "https://github.com/CosmWasm/cw-multi-test"
homepage = "https://cosmwasm.com"
license = "Apache-2.0"
edition = "2021"

[features]
default = ["cosmwasm_2_0"]
backtrace = ["anyhow/backtrace"]
cosmwasm_2_0 = ["cosmwasm-std/cosmwasm_2_0"]

[dependencies]
anyhow = "1.0.82"
bech32 = "0.11.0"
cosmwasm-std = { version = "2.0.2", features = [
    "iterator",
    "staking",
    "stargate",
] }
cw-storage-plus = "2.0.0"
cw-utils = "2.0.0"
derivative = "2.2.0"
itertools = "0.12.1"
prost = "0.12.4"
schemars = "0.8.17"
serde = "1.0.199"
sha2 = "0.10.8"
thiserror = "1.0.59"

serde_json = "1.0.40"
cosmwasm-schema = "2.0.3"
log = "0.4.20"
cw20-ics20 = "2.0.0"
hex = "0.4.3"

[dev-dependencies]
hex = "0.4.3"
hex-literal = "0.4.1"
once_cell = "1.19.0"

polytone-note = { version = "1.0.0" }
polytone-voice = { version = "1.0.0" }
polytone-proxy = { version = "1.0.0" }
polytone = { version = "1.0.0" }
