[package]
name = "cw-multi-test"
version = "2.0.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2021"
description = "Testing tools for multi-contract interactions"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-multi-test"
homepage = "https://cosmwasm.com"

[features]
default = ["cosmwasm_2_0"]
backtrace = ["anyhow/backtrace"]
cosmwasm_1_1 = ["cosmwasm-std/cosmwasm_1_1"]
cosmwasm_1_2 = ["cosmwasm_1_1", "cosmwasm-std/cosmwasm_1_2"]
cosmwasm_1_3 = ["cosmwasm_1_2", "cosmwasm-std/cosmwasm_1_3"]
cosmwasm_1_4 = ["cosmwasm_1_3", "cosmwasm-std/cosmwasm_1_4"]
cosmwasm_2_0 = ["cosmwasm_1_4", "cosmwasm-std/cosmwasm_2_0"]

[dependencies]
anyhow = "1.0.79"
bech32 = "0.9.1"
# cosmwasm-std = { version = "2.0.0-rc.0", features = ["iterator", "staking", "stargate"] }
cosmwasm-std = { path = "../cosmwasm/packages/std", features = ["iterator", "staking", "stargate"] }
cw-storage-plus = { path = "../cw-storage-plus"}
cw-utils = { path = "../cw-utils"}
derivative = "2.2.0"
itertools = "0.12.1"
prost = "0.12.3"
schemars = "0.8.16"
serde = "1.0.196"
sha2 = "0.10.8"
thiserror = "1.0.56"

[dev-dependencies]
hex = "0.4.3"
hex-literal = "0.4.1"
once_cell = "1.19.0"
