[package]
name = "cw-multi-test"
version = "2.0.0-rc.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
description = "Testing tools for multi-contract interactions"
repository = "https://github.com/CosmWasm/cw-multi-test"
homepage = "https://cosmwasm.com"
license = "Apache-2.0"
edition = "2021"

[features]
default = ["cosmwasm_2_0"]
backtrace = ["anyhow/backtrace"]
cosmwasm_2_0 = ["cosmwasm-std/cosmwasm_2_0"]

[dependencies]
anyhow = "1.0.79"
bech32 = "0.9.1"
cosmwasm-std = { version = "2.0.0-rc.1", features = ["iterator", "staking", "stargate"] }
cw-storage-plus = "2.0.0-rc.0"
cw-utils = "2.0.0-rc.0"
derivative = "2.2.0"
itertools = "0.12.1"
prost = "0.12.3"
schemars = "0.8.16"
serde = "1.0.196"
sha2 = "0.10.8"
thiserror = "1.0.56"

[dev-dependencies]
hex = "0.4.3"
hex-literal = "0.4.1"
once_cell = "1.19.0"
