[package]
name = "cw-multi-test"
version = "0.16.5"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2021"
description = "Test helpers for multi-contract interactions"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-multi-test"
homepage = "https://cosmwasm.com"

[features]
default = ["iterator", "staking", "cosmwasm_1_1"]
iterator = ["cosmwasm-std/iterator"]
stargate = ["cosmwasm-std/stargate"]
staking = ["cosmwasm-std/staking"]
backtrace = ["anyhow/backtrace"]
cosmwasm_1_1 = ["cosmwasm-std/cosmwasm_1_1"]
cosmwasm_1_2 = ["cosmwasm_1_1", "cosmwasm-std/cosmwasm_1_2"]
cosmwasm_1_3 = ["cosmwasm_1_2", "cosmwasm-std/cosmwasm_1_3"]
cosmwasm_1_4 = ["cosmwasm_1_3", "cosmwasm-std/cosmwasm_1_4"]
# This experimental feature enables stable API to be released in version 1.0 of Multi Test.
# We created this feature to provide as soon as possible a deeper insight into the Multi Test API 1.0.
# Until version 1.0 of Multi Test is officially released, please consider this feature as experimental
# and a subject to change at any time.
# DO NOT enable this feature while testing production ready smart contracts.
multitest_api_1_0 = []

[dependencies]
cw-utils = "1.0"
cw-storage-plus = "1.1"
cosmwasm-std = { version = "1.4", features = ["staking", "stargate"] }
itertools = "0.11"
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }
prost = "0.11"
anyhow = "1.0"
thiserror = "1.0"
derivative = "2"
sha2 = "0.10"

[dev-dependencies]
# We don't use the following dependency directly,
# we tighten the version so that builds with `-Zminimal-versions` work.
serde_json = "1.0.105"